/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GlucoseLogInput = IDL.Record({
  'value' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GlucoseLog = IDL.Record({
  'id' : IDL.Nat,
  'value' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const GlucoseSummary = IDL.Record({
  'lowLast7Days' : IDL.Opt(IDL.Nat),
  'highLast7Days' : IDL.Opt(IDL.Nat),
  'lastReading' : IDL.Opt(GlucoseLog),
  'avgLast7Days' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addGlucoseLog' : IDL.Func([GlucoseLogInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGlucoseLog' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlucoseLogs' : IDL.Func([], [IDL.Vec(GlucoseLog)], ['query']),
  'getGlucoseSummary' : IDL.Func([], [GlucoseSummary], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GlucoseLogInput = IDL.Record({
    'value' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GlucoseLog = IDL.Record({
    'id' : IDL.Nat,
    'value' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const GlucoseSummary = IDL.Record({
    'lowLast7Days' : IDL.Opt(IDL.Nat),
    'highLast7Days' : IDL.Opt(IDL.Nat),
    'lastReading' : IDL.Opt(GlucoseLog),
    'avgLast7Days' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addGlucoseLog' : IDL.Func([GlucoseLogInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGlucoseLog' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlucoseLogs' : IDL.Func([], [IDL.Vec(GlucoseLog)], ['query']),
    'getGlucoseSummary' : IDL.Func([], [GlucoseSummary], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };